# Generated by Django 3.0.8 on 2022-06-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('drafts', 'drafts'), ('Published', 'Published')], default='published', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
